Реализовал методы обработки url
vvkosty/go_sprint_1 pull request #1
Opened 2022-02-05 08:19 UTC by vvkosty

2022-02-06 15:09 UTC, ASPecherkin commented
Всё хорошо, код понятен и хорошо структурирован. 

Есть ещё одно мелкое замечание, но оно скорее относится к настройке IDE 

Пример с импортами 
```go
import (
	"github.com/stretchr/testify/require"
	"github.com/vvkosty/go_sprint_1/cmd/shortener/handlers"
	"github.com/vvkosty/go_sprint_1/cmd/shortener/server"
	"github.com/vvkosty/go_sprint_1/cmd/shortener/storage"
	"io"
	"testing"
)
``` 
Они отсортированы алфавитном образом, но лучше их сортировать по отношению к проекту - стандартная библиотека, локальные пакеты, внешние пакеты.
Для этого в больших проектах используется линтер goimports на сохранение файла и это поддерживает их в одинаковом порядке 

Будет прекрасно, если настроишь его для своей IDE

2022-02-06 15:10 UTC, ASPecherkin requested changes

2022-02-06 15:10 UTC, ASPecherkin commented on cmd/shortener/handlers/handlers.go
> +		c.Status(http.StatusTemporaryRedirect)
Тут можно написать чуть-чуть чище, по аналогии с PostHandler  выйти раньше, если мы уже получили URL. 

В дальнейшем в зависимости от ошибки из repository сможем сделать switch для ответа 
```go
if len(originalUrl) > 0 {
		c.Header(`Location`, originalUrl)
		c.Status(http.StatusTemporaryRedirect)
                return 
}
c.Status(http.StatusBadRequest)
```

2022-02-07 07:53 UTC, vvkosty commented
> Всё хорошо, код понятен и хорошо структурирован.
> 
> Есть ещё одно мелкое замечание, но оно скорее относится к настройке IDE
> 
> Пример с импортами
> 
> ```go
> import (
> 	"github.com/stretchr/testify/require"
> 	"github.com/vvkosty/go_sprint_1/cmd/shortener/handlers"
> 	"github.com/vvkosty/go_sprint_1/cmd/shortener/server"
> 	"github.com/vvkosty/go_sprint_1/cmd/shortener/storage"
> 	"io"
> 	"testing"
> )
> ```
> 
> Они отсортированы алфавитном образом, но лучше их сортировать по отношению к проекту - стандартная библиотека, локальные пакеты, внешние пакеты. Для этого в больших проектах используется линтер goimports на сохранение файла и это поддерживает их в одинаковом порядке
> 
> Будет прекрасно, если настроишь его для своей IDE



> Всё хорошо, код понятен и хорошо структурирован.
> 
> Есть ещё одно мелкое замечание, но оно скорее относится к настройке IDE
> 
> Пример с импортами
> 
> ```go
> import (
> 	"github.com/stretchr/testify/require"
> 	"github.com/vvkosty/go_sprint_1/cmd/shortener/handlers"
> 	"github.com/vvkosty/go_sprint_1/cmd/shortener/server"
> 	"github.com/vvkosty/go_sprint_1/cmd/shortener/storage"
> 	"io"
> 	"testing"
> )
> ```
> 
> Они отсортированы алфавитном образом, но лучше их сортировать по отношению к проекту - стандартная библиотека, локальные пакеты, внешние пакеты. Для этого в больших проектах используется линтер goimports на сохранение файла и это поддерживает их в одинаковом порядке
> 
> Будет прекрасно, если настроишь его для своей IDE

настроил, правки залил

2022-02-08 09:35 UTC, ASPecherkin approved these changes

2022-02-08 13:05 UTC, merged